package io.solarconnect.security.core.config

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer

class TestWebSecurityInitializer : AbstractSecurityWebApplicationInitializer()